name: TableTopTunes CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USE_IN_MEMORY: "true"
      DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      JWT_ISSUER: "https://yourapp.com"
      JWT_AUDIENCE: "https://yourapp.com"
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Clean the project
        run: dotnet clean

      - name: Restore dependencies
        run: dotnet restore

      - name: Build 
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --configuration Release --no-build --framework net8.0 --verbosity normal

      - name: Start ASP.NET Core app
        run: |
          nohup dotnet run --configuration Release --project ./TTTBackend/TTTBackend.csproj --urls "https://localhost:7041" &
          sleep 10
          
      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg2
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Run soak test
        run: |
          cd TTTBackend.Tests/Load
          k6 run soaktest.js --insecure-skip-tls-verify
          
      - name: Run load test
        run: |
          cd TTTBackend.Tests/Load
          k6 run loadtest.js --insecure-skip-tls-verify

      - name: Run spike test
        run: |
          cd TTTBackend.Tests/Load
          k6 run spiketest.js --insecure-skip-tls-verify
